// Code generated by "stringer -type=enums,Direction,Edge,State,PullMode"; DO NOT EDIT

package gpio

import "fmt"

const _enums_name = "dummy"

var _enums_index = [...]uint8{0, 5}

func (i enums) String() string {
	if i >= enums(len(_enums_index)-1) {
		return fmt.Sprintf("enums(%d)", i)
	}
	return _enums_name[_enums_index[i]:_enums_index[i+1]]
}

const _Direction_name = "DirectionInDirectionOut"

var _Direction_index = [...]uint8{0, 11, 23}

func (i Direction) String() string {
	if i >= Direction(len(_Direction_index)-1) {
		return fmt.Sprintf("Direction(%d)", i)
	}
	return _Direction_name[_Direction_index[i]:_Direction_index[i+1]]
}

const _Edge_name = "EdgeNoneEdgeRisingEdgeFallingEdgeBoth"

var _Edge_index = [...]uint8{0, 8, 18, 29, 37}

func (i Edge) String() string {
	if i >= Edge(len(_Edge_index)-1) {
		return fmt.Sprintf("Edge(%d)", i)
	}
	return _Edge_name[_Edge_index[i]:_Edge_index[i+1]]
}

const _State_name = "StateHighStateLow"

var _State_index = [...]uint8{0, 9, 17}

func (i State) String() string {
	if i >= State(len(_State_index)-1) {
		return fmt.Sprintf("State(%d)", i)
	}
	return _State_name[_State_index[i]:_State_index[i+1]]
}

const _PullMode_name = "PullNonePullUpPullDown"

var _PullMode_index = [...]uint8{0, 8, 14, 22}

func (i PullMode) String() string {
	if i >= PullMode(len(_PullMode_index)-1) {
		return fmt.Sprintf("PullMode(%d)", i)
	}
	return _PullMode_name[_PullMode_index[i]:_PullMode_index[i+1]]
}
